#! /usr/bin/python

import sys


def get_word_value(f):
    t = f.read(4)
    if len(t) != 4:
        return 0
    return ((ord(t[3]) << 24) | (ord(t[2]) << 16) | (ord(t[1]) << 8)
            | ord(t[0]))


def read_comments(filename):
    f = open(filename, "r")
    r = {}
    for line in f:
        if line.startswith("Register "):
            parts = line.split(' ')
            reg = eval(parts[1])
            page = eval(parts[3].strip(','))
            r.setdefault(page, {})
            r[page][reg] = eval(" ".join(parts[5:]))
    return r


def print_information(filename, info_filename):
    comments = read_comments(info_filename)
    f = open(filename, "rb")

    f.seek(0, 2)
    size = f.tell()
    f.seek(0)
    r = {}
    while f.tell() < size:
        reg = get_word_value(f)
        data = get_word_value(f)
        if reg == 0xf0:
            page = data
        else:
            r.setdefault(page, {})
            comment = comments.get(page, {}).get(reg, None)
            r[page][reg] = (data, comment)
            if comment is not None:
                sdata = str(data)
                sdata = (10 - len(sdata)) * ' ' + sdata
                print 'Page 0x%0.2X Register 0x%0.2X Value %s "%s"' % (page, reg, sdata, comment)
    return r

print "\nInformation translated from:\nhttp://code.google.com/p/yuandao-n90-window-dual-core-2/source/browse/drivers/input/touchscreen/gslx680_ts.h\n\n"

info = print_information(sys.argv[1], "firmware_information.txt")

height = info[0xfb][0x24][0]
width = info[0xfb][0x28][0]
max_touches = info[0xfa][0x04][0]

print "\n\nResolution of screen in firmware: %ix%i max touches %i\n" % (width, height, max_touches)

